Install Docker in Pipeline Visualiser workflow
The GitHub Actions arm64 runner does not have Docker installed by
default, so we must install it. The workflow also includes a test
for when we can remove it.

diff --git a/.github/workflows/pipeline-visualiser.yml b/.github/workflows/pipeline-visualiser.yml
--- a/.github/workflows/pipeline-visualiser.yml
+++ b/.github/workflows/pipeline-visualiser.yml
@@ -16,6 +16,34 @@ jobs:
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
+
+      - name: Fail if Docker is already installed
+        run: |
+          if which docker; then
+            # https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-error-message
+            echo "::error::Docker is already installed and we should default to using the included version. Remove the 'Install Docker' step from this workflow"
+            exit 1
+          fi
+
+      # This step is needed because the current GitHub arm64 runner doesn't have Docker pre-installed
+      - name: Install Docker
+        run: |
+          # shellcheck disable=SC1091
+          sudo apt-get update
+          sudo apt-get -y install ca-certificates curl
+          sudo install -m 0755 -d /etc/apt/keyrings
+          sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
+          sudo chmod a+r /etc/apt/keyrings/docker.asc
+          echo \
+          "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
+          $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
+          sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
+          sudo apt-get update
+          sudo apt-get -y install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
+          sudo usermod -a -G docker "${USER}"
+          sudo apt-get install acl
+          sudo setfacl --modify "user:${USER}:rw" /var/run/docker.sock
+
       - name: Run docker build
         run: docker build .
 
