Skip tests that depend on YQ in GitHub Actions
YQ fixed the regression that caused us problems recently, and the version has
been updated in GHA, but this version ALSO has a regression that causes us
problemsa.

diff --git a/.github/workflows/shell-ci.yml b/.github/workflows/shell-ci.yml
--- a/.github/workflows/shell-ci.yml
+++ b/.github/workflows/shell-ci.yml
@@ -24,8 +24,8 @@ jobs:
 
       - name: Lint shell scripts in GitHub actions
         run: |
-          if yq --version | grep "4.45.2" ; then
-            echo "Skipping because version 4.45.2 is buggy and makes these tests fails erroneously";
+          if yq --version | grep "4.45.4" ; then
+            echo "Skipping because version 4.45.4 is buggy and makes these tests fails erroneously";
             exit 0;
           fi
           
@@ -56,7 +56,7 @@ jobs:
 
       - name: Alert us when it's time to remove the YQ version check
         run: |
-          if ! yq --version | grep "4.45.2" ; then
-            echo "Version 4.45.2 is no longer the default yq version. We should remove our check"
+          if ! yq --version | grep "4.45.4" ; then
+            echo "Version 4.45.4 is no longer the default yq version. We should remove our check"
             exit 1
           fi
